spring:
  h2:
    console:
      enabled: true

hostname: placeholder

logging:
  level:
    org.springframework.data: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

springdoc:
  swagger-ui:
    path: /