spring:
  h2:
    console:
      enabled: true
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource

hostname: placeholder

logging:
  level:
    org.springframework.data: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

springdoc:
  swagger-ui:
    path: /